// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           18
// Async Callback (empty):               1
// Total number of exported functions:  21

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    voting_app
    (
        init => init
        upgrade => upgrade
        createElection => create_election
        createElectionWithMerkle => create_election_with_merkle
        setEncryptionPublicKey => set_encryption_public_key
        addVoters => add_voters
        endElection => end_election
        forceEndElection => force_end_election
        vote => vote
        voteWithMerkle => vote_with_merkle
        voteEncrypted => vote_encrypted
        verifyMerkleProof => verify_merkle_proof
        getAllElections => get_all_elections
        isOrganizer => is_organizer
        getElectionResults => get_election_results
        getElectionCandidates => get_election_candidates
        getEncryptionPublicKey => get_encryption_public_key
        getEligibleVoters => get_eligible_voters
        getEncryptedVotes => get_encrypted_votes
        publishResults => publish_results
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
