// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    voting_app
    (
        init => init
        upgrade => upgrade
        createElection => create_election
        createElectionWithMerkle => create_election_with_merkle
        addVoters => add_voters
        endElection => end_election
        forceEndElection => force_end_election
        vote => vote
        voteWithMerkleProof => vote_with_merkle_proof
        verifyMerkleProof => verify_merkle_proof
        getAllElections => get_all_elections
        isOrganizer => is_organizer
        getElectionResults => get_election_results
        getElectionCandidates => get_election_candidates
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
